package cn.com.chinatelecom.wsdl.ctcc.sms.receive.v2_1.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import cn.com.chinatelecom.wsdl.ctcc.sms.receive.v2_1._interface.ReceiveSms;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-09T20:00:01.717+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "ReceiveSmsService", 
                  wsdlLocation = "file:sms-wsdl/ctcc_sms_receive_service_2_1.wsdl",
                  targetNamespace = "http://www.chinatelecom.com.cn/wsdl/ctcc/sms/receive/v2_1/service") 
public class ReceiveSmsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.chinatelecom.com.cn/wsdl/ctcc/sms/receive/v2_1/service", "ReceiveSmsService");
    public final static QName ReceiveSms = new QName("http://www.chinatelecom.com.cn/wsdl/ctcc/sms/receive/v2_1/service", "ReceiveSms");
    static {
        URL url = null;
        try {
            url = new URL("file:sms-wsdl/ctcc_sms_receive_service_2_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReceiveSmsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:sms-wsdl/ctcc_sms_receive_service_2_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReceiveSmsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReceiveSmsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiveSmsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReceiveSmsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReceiveSmsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReceiveSmsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ReceiveSms
     */
    @WebEndpoint(name = "ReceiveSms")
    public ReceiveSms getReceiveSms() {
        return super.getPort(ReceiveSms, ReceiveSms.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveSms
     */
    @WebEndpoint(name = "ReceiveSms")
    public ReceiveSms getReceiveSms(WebServiceFeature... features) {
        return super.getPort(ReceiveSms, ReceiveSms.class, features);
    }

}
