package cn.com.chinatelecom.wsdl.ctcc.sms.send.v2_1._interface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-09T20:00:03.906+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.chinatelecom.com.cn/wsdl/ctcc/sms/send/v2_1/interface", name = "SendSms")
@XmlSeeAlso({cn.com.chinatelecom.schema.ctcc.sms.send.v2_1.local.ObjectFactory.class, cn.com.chinatelecom.schema.ctcc.sms.v2_1.ObjectFactory.class, cn.com.chinatelecom.schema.ctcc.common.v2_1.ObjectFactory.class})
public interface SendSms {

    @WebResult(name = "result", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
    @RequestWrapper(localName = "sendSms", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.send.v2_1.local.SendSms")
    @WebMethod
    @ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.send.v2_1.local.SendSmsResponse")
    public java.lang.String sendSms(
        @WebParam(name = "addresses", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        java.util.List<java.lang.String> addresses,
        @WebParam(name = "senderName", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        java.lang.String senderName,
        @WebParam(name = "charging", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        cn.com.chinatelecom.schema.ctcc.common.v2_1.ChargingInformation charging,
        @WebParam(name = "message", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        java.lang.String message,
        @WebParam(name = "receiptRequest", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        cn.com.chinatelecom.schema.ctcc.common.v2_1.SimpleReference receiptRequest
    ) throws cn.com.chinatelecom.wsdl.ctcc.common.v2_0.faults.ServiceException, cn.com.chinatelecom.wsdl.ctcc.common.v2_0.faults.PolicyException;

    @WebResult(name = "result", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
    @RequestWrapper(localName = "getSmsDeliveryStatus", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.send.v2_1.local.GetSmsDeliveryStatus")
    @WebMethod
    @ResponseWrapper(localName = "getSmsDeliveryStatusResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.send.v2_1.local.GetSmsDeliveryStatusResponse")
    public java.util.List<cn.com.chinatelecom.schema.ctcc.sms.v2_1.DeliveryInformation> getSmsDeliveryStatus(
        @WebParam(name = "requestIdentifier", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        java.lang.String requestIdentifier
    ) throws cn.com.chinatelecom.wsdl.ctcc.common.v2_0.faults.ServiceException, cn.com.chinatelecom.wsdl.ctcc.common.v2_0.faults.PolicyException;

    @WebResult(name = "result", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
    @RequestWrapper(localName = "sendSmsLogo", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.send.v2_1.local.SendSmsLogo")
    @WebMethod
    @ResponseWrapper(localName = "sendSmsLogoResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.send.v2_1.local.SendSmsLogoResponse")
    public java.lang.String sendSmsLogo(
        @WebParam(name = "addresses", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        java.util.List<java.lang.String> addresses,
        @WebParam(name = "senderName", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        java.lang.String senderName,
        @WebParam(name = "charging", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        cn.com.chinatelecom.schema.ctcc.common.v2_1.ChargingInformation charging,
        @WebParam(name = "image", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        byte[] image,
        @WebParam(name = "smsFormat", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        cn.com.chinatelecom.schema.ctcc.sms.v2_1.SmsFormat smsFormat,
        @WebParam(name = "receiptRequest", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        cn.com.chinatelecom.schema.ctcc.common.v2_1.SimpleReference receiptRequest
    ) throws cn.com.chinatelecom.wsdl.ctcc.common.v2_0.faults.ServiceException, cn.com.chinatelecom.wsdl.ctcc.common.v2_0.faults.PolicyException;

    @WebResult(name = "result", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
    @RequestWrapper(localName = "sendSmsRingtone", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.send.v2_1.local.SendSmsRingtone")
    @WebMethod
    @ResponseWrapper(localName = "sendSmsRingtoneResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.send.v2_1.local.SendSmsRingtoneResponse")
    public java.lang.String sendSmsRingtone(
        @WebParam(name = "addresses", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        java.util.List<java.lang.String> addresses,
        @WebParam(name = "senderName", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        java.lang.String senderName,
        @WebParam(name = "charging", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        cn.com.chinatelecom.schema.ctcc.common.v2_1.ChargingInformation charging,
        @WebParam(name = "ringtone", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        java.lang.String ringtone,
        @WebParam(name = "smsFormat", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        cn.com.chinatelecom.schema.ctcc.sms.v2_1.SmsFormat smsFormat,
        @WebParam(name = "receiptRequest", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
        cn.com.chinatelecom.schema.ctcc.common.v2_1.SimpleReference receiptRequest
    ) throws cn.com.chinatelecom.wsdl.ctcc.common.v2_0.faults.ServiceException, cn.com.chinatelecom.wsdl.ctcc.common.v2_0.faults.PolicyException;
}
