
package cn.com.chinatelecom.wsdl.ctcc.common.v2_0.faults;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-09T20:00:03.899+08:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "PolicyException", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/common/v2_1")
public class PolicyException extends Exception {
    
    private cn.com.chinatelecom.schema.ctcc.common.v2_1.PolicyException policyException;

    public PolicyException() {
        super();
    }
    
    public PolicyException(String message) {
        super(message);
    }
    
    public PolicyException(String message, Throwable cause) {
        super(message, cause);
    }

    public PolicyException(String message, cn.com.chinatelecom.schema.ctcc.common.v2_1.PolicyException policyException) {
        super(message);
        this.policyException = policyException;
    }

    public PolicyException(String message, cn.com.chinatelecom.schema.ctcc.common.v2_1.PolicyException policyException, Throwable cause) {
        super(message, cause);
        this.policyException = policyException;
    }

    public cn.com.chinatelecom.schema.ctcc.common.v2_1.PolicyException getFaultInfo() {
        return this.policyException;
    }
}
