
package cn.com.chinatelecom.wsdl.ctcc.common.v2_0.faults;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-09T20:00:03.870+08:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "ServiceException", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/common/v2_1")
public class ServiceException extends Exception {
    
    private cn.com.chinatelecom.schema.ctcc.common.v2_1.ServiceException serviceException;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, cn.com.chinatelecom.schema.ctcc.common.v2_1.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException(String message, cn.com.chinatelecom.schema.ctcc.common.v2_1.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public cn.com.chinatelecom.schema.ctcc.common.v2_1.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
