package cn.com.chinatelecom.wsdl.ctcc.sms.notification.v2_1._interface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-09T19:59:57.272+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.chinatelecom.com.cn/wsdl/ctcc/sms/notification/v2_1/interface", name = "SmsNotification")
@XmlSeeAlso({cn.com.chinatelecom.schema.ctcc.sms.notification.v2_1.local.ObjectFactory.class, cn.com.chinatelecom.schema.ctcc.sms.v2_1.ObjectFactory.class, cn.com.chinatelecom.schema.ctcc.common.v2_1.ObjectFactory.class})
public interface SmsNotification {

    @RequestWrapper(localName = "notifySmsDeliveryReceipt", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/notification/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.notification.v2_1.local.NotifySmsDeliveryReceipt")
    @WebMethod
    @ResponseWrapper(localName = "notifySmsDeliveryReceiptResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/notification/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.notification.v2_1.local.NotifySmsDeliveryReceiptResponse")
    public void notifySmsDeliveryReceipt(
        @WebParam(name = "correlator", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/notification/v2_1/local")
        java.lang.String correlator,
        @WebParam(name = "deliveryStatus", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/notification/v2_1/local")
        cn.com.chinatelecom.schema.ctcc.sms.v2_1.DeliveryInformation deliveryStatus
    );

    @RequestWrapper(localName = "notifySmsReception", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/notification/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.notification.v2_1.local.NotifySmsReception")
    @WebMethod
    @ResponseWrapper(localName = "notifySmsReceptionResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/notification/v2_1/local", className = "cn.com.chinatelecom.schema.ctcc.sms.notification.v2_1.local.NotifySmsReceptionResponse")
    public void notifySmsReception(
        @WebParam(name = "correlator", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/notification/v2_1/local")
        java.lang.String correlator,
        @WebParam(name = "message", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/notification/v2_1/local")
        cn.com.chinatelecom.schema.ctcc.sms.v2_1.SmsMessage message
    );
}
